INSERT INTO studenten (student_id, voornaam, achternaam , klas, adres, postcode, geboortedatum, woonplaats)
VALUES (5,'Piet', 'Pieters', '9A', 	'Albert Cuypstraat 5' ,	'1234AB', '2001-04-28',	'Ouderkerk')
INSERT INTO studenten (student_id, voornaam, achternaam , klas, adres, postcode, geboortedatum, woonplaats)
VALUES (6,'Johanna', 'Eduardo', '9C', 	'Pieter Aertzstraat 44' ,	'1073CD', '2001-09-02',	'Hoorn')
INSERT INTO studenten (student_id, voornaam, achternaam , klas, adres, postcode, geboortedatum, woonplaats)
VALUES (7,'Angela', 'Mohammed', '9C', 	'Piet Mondriaanplein 14' ,	'1299CD', '2002-05-17',	'Amstelveen')
